#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#define ROBOT_BOARD_GIMBAL  1
#define ROBOT_BOARD_CHASSIS 2

#ifndef ROBOT_BOARD
#define ROBOT_BOARD ROBOT_BOARD_GIMBAL
#endif

#if (ROBOT_BOARD != ROBOT_BOARD_GIMBAL) && (ROBOT_BOARD != ROBOT_BOARD_CHASSIS)
#error "ROBOT_BOARD must be ROBOT_BOARD_GIMBAL or ROBOT_BOARD_CHASSIS"
#endif

#define BOARD_IS_GIMBAL  (ROBOT_BOARD == ROBOT_BOARD_GIMBAL)
#define BOARD_IS_CHASSIS (ROBOT_BOARD == ROBOT_BOARD_CHASSIS)

#endif
